apiVersion: v1
kind: Service
metadata:
  name: bms-service
  namespace: yash-dev-namespace
  labels:
    app: bms
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  selector:
    app: bms
